# Site settings
title: yhoshino11's blog
description: 'blog by open source developer in Japan.'
url: 'https://yhoshino11.github.io'
baseurl: '/'
google_analytics: 'UA-80588410-1'
disqus_shortname: 'yhoshino11'

author:
  name: 'Yu Hoshino'
  email: yhoshino11@gmail.com
  twitter_username: yhoshino11
  github_username:  yhoshino11

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
